resolver: lts-13.23
packages:
- .
extra-deps:
- bloomfilter-2.0.1.0@sha256:5b67d765315fb2abc1cde85e3c20ae1badfbe8d1070ed57525b7c428586e2d2f
- lrucache-1.2.0.1@sha256:18fc3d7052012c7ab3cd395160f34b53c5e1ec5379cc45185baf35b90ffadc2e
# flags: {}
# extra-package-dbs: []
# system-ghc: true
# require-stack-version: -any # Default
# require-stack-version: ">=1.9"
# arch: i386
# arch: x86_64
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
# compiler-check: newer-minor
